name: automatic
channels:
  - pytorch-nightly
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>3.11
  - pip>=23.0
  - cudatoolkit>=12.0
  - pytorch>=2.0
  - torchvision>=0.15
  - numpy>=1.25
